Pract 92/update styling navbar add logout route find logo app name
Code-the-Dream-School/ee-prac-team4-front pull request #26
Opened 2023-12-09 06:10 UTC by koral14

_For an example of how to fill this template out, [see this Pull Request](https://github.com/the-collab-lab/tcl-3-smart-shopping-list/pull/44)._

## Description

Updated styling for the navbar, added logo, login, resources and logout icons. The logo takes to the main page, the login takes you to the main page, the logout takes to the login page. 

## Related Issue

## Acceptance Criteria

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: Update UI     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Updates

### Before

![image](https://github.com/Code-the-Dream-School/ee-prac-team4-front/assets/105457134/400124d8-2b5e-4068-a039-9d05cee26e19)

### After

![image](https://github.com/Code-the-Dream-School/ee-prac-team4-front/assets/105457134/7d82fea8-5844-48a2-9af6-c48dbb8c85c2)

## Testing Steps / QA Criteria

© 2022 GitHub, Inc.
Terms
Privacy
Security
Status

2023-12-12 15:53 UTC, nikkigraybeal commented on src/pages/register/Register.js
Can you make the registration form a little bit shorter? Right now the title is slightly hidden by the navbar on my desktop screen. It might just need a little top margin instead of making it shorter?

2023-12-12 16:14 UTC, nikkigraybeal requested changes
This is looking great, Olga! Awesome job, as always 😃 A few things to address but it's super close.

Can you cahnge the background of home page and resources page to match the background on the login and register pages?

DOn't forget to merge main and resolve any conflicts.

2023-12-12 16:14 UTC, nikkigraybeal commented on src/components/navbar/Navbar.css
- put a bit of space between the page links "Resources" and "About" and make the font slightly bigger
- I know that crowds things at ~600px width though. Maybe the space between the auth buttons could be less to help give more room?
- I think LOG-IN should be LOGIN and SIGN-UP should be REGISTER for the auth buttons
- hamburger menu slides of left side of page below 400px - keep it onscreen to 320px
- if you can get the hamburger to be aligned with left side of page that would be great but not a priority!

2023-12-12 16:14 UTC, nikkigraybeal commented on src/components/navbar/Navbar.js
- click on "X" doesn't close the hamburger (click outside of menu works great though!)

2023-12-12 22:43 UTC, koral14 commented on public/favicon.ico
Replaced the favicon with the computer that we are using in the logo. Let me know what you think. I didn't want to put the entire logo because it has to be small and square or round...

2023-12-12 23:57 UTC, koral14 commented on src/components/navbar/Navbar.css
* I added space between the Resources and About and increased the font;
* changed the auth button names as suggested
* I didn't notice the hamburger menu sliding off left side of page below 400px (could you please send me some screenshots)
* changing it on the left side would be very challenging on this stage. A lot of styling would be required to change. This could take a lot of time. Let's leave it for the end, in case we will have time before presentation.

2023-12-13 03:30 UTC, koral14 commented on src/components/navbar/Navbar.js
Yes, this is the issue with this 'hand-made' hamburger. I can make the X close the hamburger, but then when clicking outside won't work. I can have only one option at a time. I tried different variations and none of them worked together, so I made the navbar also clickable. The only not clickable place on the screen is the X :)

2023-12-14 17:13 UTC, madebymiguel approved these changes
Overall it looks good to me. Fix the about link url to take you to /about instead of /.

2023-12-14 17:13 UTC, merged