pract-78-create a deck display card, pract-70-update homepage styling
Code-the-Dream-School/ee-prac-team4-front pull request #28
Opened 2023-12-11 04:08 UTC by elenademi

## Description

This PR creates and formats a deck display card (Jira ticket 78) and updates styling of the home page based on the Figma prototype.

## Related Issue

## Acceptance Criteria

The styling should use the UI kit and follow the Figma wireframes.
The deck card should display the title of the deck, the topic, and the number of cards.

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|     | :bug: Bug fix              |
| ✓   | :sparkles: New feature     |
|     | :hammer: Refactoring       |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

![Screenshot 2023-12-10 200540](https://github.com/Code-the-Dream-School/ee-prac-team4-front/assets/118300498/df7bff74-58a4-4424-b5fb-a0f567d0c9cf)

© 2022 GitHub, Inc.
Terms
Privacy
Security
Status

2023-12-12 22:31 UTC, nikkigraybeal requested changes
The Deck card is looking really nice, Elena! Great work! 
There is margin being automatically applied to the content of the card and is making it too tall, I think. Also, we can use some adjustment on width. See comments for each file below.

2023-12-12 22:31 UTC, nikkigraybeal commented on src/components/deckCard/DeckCard.css
- add `margin: 5px;` to all elements rendered inside of .deck-card
- hardcode .h3-deck-card with `font-size: 20px;`
- replace `width: 40%` with `width: 300px;` in .deck-card
- remove the media query from this file

2023-12-12 22:31 UTC, nikkigraybeal commented on src/pages/home/Home.css
- add `width: 100%` and `margin: 0 auto` to .decks-container
- add this media query to this file: 
```
@media (max-width: 750px) {
  .decks-container {
     justify-content: center;
  }
}
```

2023-12-13 04:03 UTC, elenademi commented
Thanks a lot for the feedback! I had to work all day today, but I'll get to
it tomorrow.

On Tue, Dec 12, 2023, 5:31 PM Nikki Graybeal ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> The Deck card is looking really nice, Elena! Great work!
> There is margin being automatically applied to the content of the card and
> is making it too tall, I think. Also, we can use some adjustment on width.
> See comments for each file below.
> ------------------------------
>
> On src/components/deckCard/DeckCard.css
> <https://github.com/Code-the-Dream-School/ee-prac-team4-front/pull/28#discussion_r1424641463>
> :
>
>    - add margin: 5px; to all elements rendered inside of .deck-card
>    - hardcode .h3-deck-card with font-size: 20px;
>    - replace width: 40% with width: 300px; in .deck-card
>    - remove the media query from this file
>
> ------------------------------
>
> On src/pages/home/Home.css
> <https://github.com/Code-the-Dream-School/ee-prac-team4-front/pull/28#discussion_r1424643721>
> :
>
>    - add width: 100% and margin: 0 auto to .decks-container
>    - add this media query to this file:
>
> @media (max-width: 750px) {
>   .decks-container {
>      justify-content: center;
>   }
> }
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Code-the-Dream-School/ee-prac-team4-front/pull/28#pullrequestreview-1778540569>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4GR6UWE6FHN6WH4FZSAU3DYJDLLPAVCNFSM6AAAAABAPDVL3OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTONZYGU2DANJWHE>
> .
> You are receiving this because you authored the thread.Message ID:
> <Code-the-Dream-School/ee-prac-team4-front/pull/28/review/1778540569@
> github.com>
>

2023-12-14 17:22 UTC, madebymiguel approved these changes
LGMT

2023-12-14 17:22 UTC, merged